development:
 adapter: mysql
 encoding: utf8
 database: portfolio_development
 username: root
 password: terminal
 socket: /tmp/mysql.sock

test:
 adapter: mysql
 encoding: utf8
 database: portfolio_test
 username: root
 password: terminal
 socket: /tmp/mysql.sock

production:
 adapter: mysql
 encoding: utf8
 database: portfolio_production
 username: root
 password: terminal
 socket: /tmp/mysql.sock
